### ISSUE TITLE
'include statement gives fatal error

### ISSUE THREAD

**Issue by greedysquid** [SystemRDL/systemrdl-compiler#65] opened 2020-09-25 13:25 UTC
I have a .rdl file with a Verilog style include statement to pull in another .rdl file:
` _backtick_include "reg_types.rdl"`
With v1.12.0 this parses, the file is included, and all compiles.
With v1.13.0 the same files give an error:
`fatal: Unexpected text after include`

**Comment by amykyta3** [comment] 2020-09-25 15:22
Strange that my unit tests did not catch this. Would it be possible to
attach an example file?

**Comment by greedysquid** [comment] 2020-09-25 15:56
Thanks for the prompt reply!
A simple stripped down test case attached.

[test-compileRDL.zip](https://github.com/SystemRDL/systemrdl-compiler/files/5283877/test-compileRDL.zip)

**Comment by amykyta3** [comment] 2020-09-25 16:02
Thanks! Ill look at it later today. Without looking at it, my hunch is that
its related to Windows newlines vs Unix newlines.

**Comment by amykyta3** [comment] 2020-09-27 04:52
Turned out to be a regression due to the new Verilog preprocessor support added in 1.13 that broke files with Windows CRLF newlines.
Just released `v1.13.1` where it should be fixed.

Thanks again for reporting!

**Closed by amykyta3** 2020-09-27 04:52 UTC
Labels: bug

**Comment by greedysquid** [comment] 2020-10-13 23:00
Apologies - I thought I had replied.
Thank you for the prompt investigation and update.
I confirm that v1.13.1 fixes this problem for me.
